# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Alex Beluberdy III Junior
title: Humble 3rd Assistant to Secretary
email: alex@beluberdy.email.com
email_title: Electric Mail
phone: +12345678987654321
phone_title: Mars Landline Switchboard
website: https://mywebsite.com
website_title: Corporate Site on World Wide Web

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: abeluberdy
github_username:  abeluberdy
stackoverflow_username: "00000001"
dribbble_username: abeluberdy
facebook_username: abeluberdy
flickr_username: abeluberdy
instagram_username: abeluberdy
linkedin_username: abeluberdy
xing_username: abeluberdy
pinterest_username: abeluberdy
youtube_username: abeluberdy
orcid_username: 1234-1234-1234-1234
googlescholar_username: abeluberdy

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About section is About Me Section
about_profile_image: images/profile.jpg
about_content: 
  This is an awesome description about myself right here, which supports markdown, so I add [links](http://abeluberdy.com) and highlight things <mark>like this</abeluberdy>.

  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
    - Lists
    - Tables
    - <a href="google.com">Links</a>
    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects Beluberdy X Projects
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project XYZ
        link: projectXYZ.com
        link_text: Direct Link
        additional_links:
          - title:  Github page for project is NOT available
            icon: fab fa-github
            url: projectXYZ.com
          - title:  Github page for project
            icon: fab fa-github
            url: projectXYZ
        quote: >
          Very long and detailed overview of the project
        description: | # this will include new lines to allow paragraphs
          It was a project on something. I don't remember
  - title: Super Humble Assistant to Intern Python Programmer
    layout: list
    content:
      - layout: right
        title: Humble People Limited
        sub_title: Sub-Assistant
        caption: 1492 - present
        link: HumblePeopleLimited.org
        quote: >
          It was a very good company
        description: | # this will include new lines to allow paragraphs
          I answered electric phone calls and made tean and coffee for myself
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Kindergarten N1234
        sub_title: Good kid qualification
        caption: 1905 - present
        quote: >
          This is a kindergarten for adult serious kids
        description: | # this will include new lines to allow paragraphs
          Behaved well (occasionally)
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where I can write a little more about myself.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
